version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "installing dependencies..."
      - npm install -g @angular/cli@13.0.0
    build:
      commands:
        - echo "building angular project...."
        - ng build --prod
    post-build:
      commands:
        - echo "updating files in s3 bucket..."
        - aws s3 sync dist/demostack/ s3://static-website-demo-007 --delete
