version: 1.0
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "installing dependencies..."
      - npm install
      - npm install -g @angular/cli@7.3.9
    build:
      commands:
        - echo "building angular project..."
        - ng build --prod
    post-build:
      commands:
        - echo "updating files in s3 bucket..."
        - aws s3 sync dist/demostack/ s3://static-website-demo-007 --delete
